### ISSUE TITLE
[load/expose] Expose only a sub-set configs from a file

### ISSUE THREAD

**Issue by 0exp** [0exp/qonfig#123]
```yaml
kek:
 pek:
    cheburek: '1'
 fek:
    balabek: '2'
```

```ruby
expose 'file_path', subset: 'kek.fek', (and etc: via, env:, ...)
# and etc
```
